// This is a simplified version. In production, you'd want a complete database
export const zipToCounty: { [key: string]: { county: string; state: string } } = {
  // Los Angeles County
  "90001": { county: "Los Angeles", state: "CA" },
  "90002": { county: "Los Angeles", state: "CA" },
  "90003": { county: "Los Angeles", state: "CA" },
  "90004": { county: "Los Angeles", state: "CA" },
  "90005": { county: "Los Angeles", state: "CA" },
  "90006": { county: "Los Angeles", state: "CA" },
  "90007": { county: "Los Angeles", state: "CA" },
  "90008": { county: "Los Angeles", state: "CA" },
  "90009": { county: "Los Angeles", state: "CA" },
  "90010": { county: "Los Angeles", state: "CA" },
  "90011": { county: "Los Angeles", state: "CA" },
  "90012": { county: "Los Angeles", state: "CA" },
  "90013": { county: "Los Angeles", state: "CA" },
  "90014": { county: "Los Angeles", state: "CA" },
  "90015": { county: "Los Angeles", state: "CA" },
  "90016": { county: "Los Angeles", state: "CA" },
  "90017": { county: "Los Angeles", state: "CA" },
  "90018": { county: "Los Angeles", state: "CA" },
  "90019": { county: "Los Angeles", state: "CA" },
  "90020": { county: "Los Angeles", state: "CA" },
  "90021": { county: "Los Angeles", state: "CA" },
  "90022": { county: "Los Angeles", state: "CA" },
  "90023": { county: "Los Angeles", state: "CA" },
  "90024": { county: "Los Angeles", state: "CA" },
  "90025": { county: "Los Angeles", state: "CA" },
  "90026": { county: "Los Angeles", state: "CA" },
  "90027": { county: "Los Angeles", state: "CA" },
  "90028": { county: "Los Angeles", state: "CA" },
  "90029": { county: "Los Angeles", state: "CA" },
  "90030": { county: "Los Angeles", state: "CA" },
  "90031": { county: "Los Angeles", state: "CA" },
  "90032": { county: "Los Angeles", state: "CA" },
  "90033": { county: "Los Angeles", state: "CA" },
  "90034": { county: "Los Angeles", state: "CA" },
  "90035": { county: "Los Angeles", state: "CA" },
  "90036": { county: "Los Angeles", state: "CA" },
  "90037": { county: "Los Angeles", state: "CA" },
  "90038": { county: "Los Angeles", state: "CA" },
  "90039": { county: "Los Angeles", state: "CA" },
  "90040": { county: "Los Angeles", state: "CA" },
  "90041": { county: "Los Angeles", state: "CA" },
  "90042": { county: "Los Angeles", state: "CA" },
  "90043": { county: "Los Angeles", state: "CA" },
  "90044": { county: "Los Angeles", state: "CA" },
  "90045": { county: "Los Angeles", state: "CA" },
  "90046": { county: "Los Angeles", state: "CA" },
  "90047": { county: "Los Angeles", state: "CA" },
  "90048": { county: "Los Angeles", state: "CA" },
  "90049": { county: "Los Angeles", state: "CA" },
  "90050": { county: "Los Angeles", state: "CA" },
  "90051": { county: "Los Angeles", state: "CA" },
  "90052": { county: "Los Angeles", state: "CA" },
  "90053": { county: "Los Angeles", state: "CA" },
  "90054": { county: "Los Angeles", state: "CA" },
  "90055": { county: "Los Angeles", state: "CA" },
  "90056": { county: "Los Angeles", state: "CA" },
  "90057": { county: "Los Angeles", state: "CA" },
  "90058": { county: "Los Angeles", state: "CA" },
  "90059": { county: "Los Angeles", state: "CA" },
  "90060": { county: "Los Angeles", state: "CA" },
  "90061": { county: "Los Angeles", state: "CA" },
  "90062": { county: "Los Angeles", state: "CA" },
  "90063": { county: "Los Angeles", state: "CA" },
  "90064": { county: "Los Angeles", state: "CA" },
  "90065": { county: "Los Angeles", state: "CA" },
  "90066": { county: "Los Angeles", state: "CA" },
  "90067": { county: "Los Angeles", state: "CA" },
  "90068": { county: "Los Angeles", state: "CA" },
  "90069": { county: "Los Angeles", state: "CA" },
  "90070": { county: "Los Angeles", state: "CA" },
  "90071": { county: "Los Angeles", state: "CA" },
  "90072": { county: "Los Angeles", state: "CA" },
  "90073": { county: "Los Angeles", state: "CA" },
  "90074": { county: "Los Angeles", state: "CA" },
  "90075": { county: "Los Angeles", state: "CA" },
  "90076": { county: "Los Angeles", state: "CA" },
  "90077": { county: "Los Angeles", state: "CA" },
  "90078": { county: "Los Angeles", state: "CA" },
  "90079": { county: "Los Angeles", state: "CA" },
  "90080": { county: "Los Angeles", state: "CA" },
  "90081": { county: "Los Angeles", state: "CA" },
  "90082": { county: "Los Angeles", state: "CA" },
  "90083": { county: "Los Angeles", state: "CA" },
  "90084": { county: "Los Angeles", state: "CA" },
  "90086": { county: "Los Angeles", state: "CA" },
  "90087": { county: "Los Angeles", state: "CA" },
  "90088": { county: "Los Angeles", state: "CA" },
  "90089": { county: "Los Angeles", state: "CA" },
  "90090": { county: "Los Angeles", state: "CA" },
  "90091": { county: "Los Angeles", state: "CA" },
  "90093": { county: "Los Angeles", state: "CA" },
  "90094": { county: "Los Angeles", state: "CA" },
  "90095": { county: "Los Angeles", state: "CA" },
  "90096": { county: "Los Angeles", state: "CA" },
  "90099": { county: "Los Angeles", state: "CA" },
  "90189": { county: "Los Angeles", state: "CA" },
  "90201": { county: "Los Angeles", state: "CA" },
  "90202": { county: "Los Angeles", state: "CA" },
  "90209": { county: "Los Angeles", state: "CA" },
  "90210": { county: "Los Angeles", state: "CA" },
  "90211": { county: "Los Angeles", state: "CA" },
  "90212": { county: "Los Angeles", state: "CA" },
  "90213": { county: "Los Angeles", state: "CA" },
  "90220": { county: "Los Angeles", state: "CA" },
  "90221": { county: "Los Angeles", state: "CA" },
  "90222": { county: "Los Angeles", state: "CA" },
  "90223": { county: "Los Angeles", state: "CA" },
  "90224": { county: "Los Angeles", state: "CA" },
  "90230": { county: "Los Angeles", state: "CA" },
  "90231": { county: "Los Angeles", state: "CA" },
  "90232": { county: "Los Angeles", state: "CA" },
  "90233": { county: "Los Angeles", state: "CA" },
  "90239": { county: "Los Angeles", state: "CA" },
  "90240": { county: "Los Angeles", state: "CA" },
  "90241": { county: "Los Angeles", state: "CA" },
  "90242": { county: "Los Angeles", state: "CA" },
  "90245": { county: "Los Angeles", state: "CA" },
  "90247": { county: "Los Angeles", state: "CA" },
  "90248": { county: "Los Angeles", state: "CA" },
  "90249": { county: "Los Angeles", state: "CA" },
  "90250": { county: "Los Angeles", state: "CA" },
  "90251": { county: "Los Angeles", state: "CA" },
  "90254": { county: "Los Angeles", state: "CA" },
  "90255": { county: "Los Angeles", state: "CA" },
  "90260": { county: "Los Angeles", state: "CA" },
  "90261": { county: "Los Angeles", state: "CA" },
  "90262": { county: "Los Angeles", state: "CA" },
  "90263": { county: "Los Angeles", state: "CA" },
  "90264": { county: "Los Angeles", state: "CA" },
  "90265": { county: "Los Angeles", state: "CA" },
  "90266": { county: "Los Angeles", state: "CA" },
  "90267": { county: "Los Angeles", state: "CA" },
  "90270": { county: "Los Angeles", state: "CA" },
  "90272": { county: "Los Angeles", state: "CA" },
  "90274": { county: "Los Angeles", state: "CA" },
  "90275": { county: "Los Angeles", state: "CA" },
  "90277": { county: "Los Angeles", state: "CA" },
  "90278": { county: "Los Angeles", state: "CA" },
  "90280": { county: "Los Angeles", state: "CA" },
  "90290": { county: "Los Angeles", state: "CA" },
  "90291": { county: "Los Angeles", state: "CA" },
  "90292": { county: "Los Angeles", state: "CA" },
  "90293": { county: "Los Angeles", state: "CA" },
  "90294": { county: "Los Angeles", state: "CA" },
  "90295": { county: "Los Angeles", state: "CA" },
  "90296": { county: "Los Angeles", state: "CA" },
  "90301": { county: "Los Angeles", state: "CA" },
  "90302": { county: "Los Angeles", state: "CA" },
  "90303": { county: "Los Angeles", state: "CA" },
  "90304": { county: "Los Angeles", state: "CA" },
  "90305": { county: "Los Angeles", state: "CA" },
  "90306": { county: "Los Angeles", state: "CA" },
  "90307": { county: "Los Angeles", state: "CA" },
  "90308": { county: "Los Angeles", state: "CA" },
  "90309": { county: "Los Angeles", state: "CA" },
  "90310": { county: "Los Angeles", state: "CA" },
  "90311": { county: "Los Angeles", state: "CA" },
  "90312": { county: "Los Angeles", state: "CA" },
  
  // Orange County
  "92601": { county: "Orange", state: "CA" },
  "92602": { county: "Orange", state: "CA" },
  "92603": { county: "Orange", state: "CA" },
  "92604": { county: "Orange", state: "CA" },
  "92605": { county: "Orange", state: "CA" },
  
  // San Francisco County
  "94101": { county: "San Francisco", state: "CA" },
  "94102": { county: "San Francisco", state: "CA" },
  "94103": { county: "San Francisco", state: "CA" },
  "94104": { county: "San Francisco", state: "CA" },
  "94105": { county: "San Francisco", state: "CA" },
  
  // Santa Clara County
  "95110": { county: "Santa Clara", state: "CA" },
  "95111": { county: "Santa Clara", state: "CA" },
  "95112": { county: "Santa Clara", state: "CA" },
  
  // San Diego County
  "92101": { county: "San Diego", state: "CA" },
  "92102": { county: "San Diego", state: "CA" },
  "92103": { county: "San Diego", state: "CA" },
  
  // Default for testing
  "00000": { county: "Unknown", state: "CA" }
};